version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: measures-backend
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    command: sh -c "npx prisma migrate dev && npm run dev"

  postgres:
    image: postgres:15
    container_name: pg_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: measures_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres-data:
